#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QtQml/QQmlContext>  // <-- Forces full type resolution explicitly
#include <QQuickStyle>
#include "renderer/renderer.h"
#include <QQuickWindow> // Required for setGraphicsApi
#include "ui/custom_viewport_item.h"

int main(int argc, char *argv[]) {
    // 1. CRITICAL: Force Qt 6 to use its native OpenGL backend
    // Otherwise, Qt Quick might default to Direct3D/Vulkan/Metal on modern OS layers.
    QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL);

    QQuickStyle::setStyle("Fusion");

    QGuiApplication app(argc, argv);

    // 2. Register your viewport item within the exact module namespace defined in CMake
    // Syntax: qmlRegisterType<CppClass>("URI", MajorVersion, MinorVersion, "QmlClassName");
    qmlRegisterType<CustomViewportItem>("RendererQTUI", 1, 0, "ViewportVisualizer");

    QQmlApplicationEngine engine;

    // Inject your renderer instance globally
    Renderer meshRenderer;
    engine.rootContext()->setContextProperty("backendRenderer", &meshRenderer);

    // Load from the exact resource URL generated by qt_add_qml_module
    const QUrl url(QStringLiteral("qrc:/RendererQTUI/ui/Main.qml"));
    //const QUrl url(QStringLiteral("qrc:/RendererQTUI/Main.qml"));

    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
                         if (!obj && url == objUrl)
                             QCoreApplication::exit(-1);
                     }, Qt::QueuedConnection);

    engine.load(url);

    return app.exec();
}