#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QtQml/QQmlContext>
#include <QQuickStyle>
#include <QQuickWindow>
#include <QDebug> // Required for logging output streams

#include "renderer/renderer.h"
#include "ui/custom_viewport_item.h"

int main(int argc, char *argv[]) {
    // Checkpoint 1: Application initialization entry point reached
    qDebug() << "[LAUNCH DIAGNOSTIC 1/6] Main entry executed. Allocating resources...";

    // 1. Force Qt 6 to use its native OpenGL backend
    QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL);
    qDebug() << "[LAUNCH DIAGNOSTIC 2/6] Graphics API explicitly bound to native OpenGL.";

    // 2. Override default styling rules to prevent customizable control runtime crashes
    QQuickStyle::setStyle("Fusion");
    qDebug() << "[LAUNCH DIAGNOSTIC 3/6] Engine fallback UI style forced to 'Fusion'.";

    QGuiApplication app(argc, argv);

    // 3. Register your viewport item within the exact module namespace defined in CMake
    qmlRegisterType<CustomViewportItem>("RendererQTUI", 1, 0, "ViewportVisualizer");
    qDebug() << "[LAUNCH DIAGNOSTIC 4/6] C++ CustomViewportItem exposed to QML runtime module mapping.";

    QQmlApplicationEngine engine;

    // Connect an explicit listener to trap inner compilation or syntax errors within QML files
    QObject::connect(&engine, &QQmlApplicationEngine::warnings, &app, [](const QList<QQmlError> &warnings) {
        for (const auto &error : warnings) {
            qCritical() << "[QML COMPILE WARNING/ERROR]:" << error.toString();
        }
    });

    // Inject your renderer instance globally
    Renderer meshRenderer;
    engine.rootContext()->setContextProperty("backendRenderer", &meshRenderer);
    qDebug() << "[LAUNCH DIAGNOSTIC 5/6] Global backendRenderer instance context property successfully injected.";

    // Load from the exact resource URL generated by qt_add_qml_module
    const QUrl url(QStringLiteral("qrc:/RendererQTUI/ui/Main.qml"));
    qDebug() << "[LAUNCH DIAGNOSTIC 6/6] Requesting QQmlApplicationEngine to parse asset track URL:" << url.toString();

    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
                         if (!obj && url == objUrl) {
                             qCritical() << "[FATAL LIFECYCLE BREAK]: QML Engine failed to compile or instantiate root object window framework.";
                             QCoreApplication::exit(-1);
                         } else {
                             qDebug() << "[SUCCESS]: Root UI window object created successfully. Main window event loop spinning up...";
                         }
                     }, Qt::QueuedConnection);

    engine.load(url);

    return app.exec();
}