#include "renderer/renderer.h"
#include "colormaps/Colormaps.h"
#include "camera/Camera.h"
#include "export/screenshot.h"
#include "mesh/mesh_loader.h"

#include <cstring>
#include <cmath>
#include <cstdio>
#include <ctime>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <algorithm>

// Qt Core & UI Utilities replacing Win32 APIs
#include <QDir>
#include <QQuickOpenGLUtils>
#include <QFileInfo>
#include <QOpenGLContext>

static bool compileShader(GLuint shader, const char* source, const char* type) {
    glShaderSource(shader, 1, &source, nullptr);
    glCompileShader(shader);
    GLint success;
    glGetShaderiv(shader, GL_COMPILE_STATUS, &success);
    if (!success) {
        char log[512];
        glGetShaderInfoLog(shader, 512, nullptr, log);
        printf("Shader compile error (%s): %s\n", type, log);
        return false;
    }
    return true;
}

Renderer::Renderer(QObject* parent)
    : QObject(parent), width(800), height(600), hasMeshLoaded(false) {

    // Default system initialization parameters
    meshColor[0] = 0.4f; meshColor[1] = 0.9f; meshColor[2] = 0.4f;
    surfaceColor[0] = 1.0f; surfaceColor[1] = 1.0f; surfaceColor[2] = 1.0f;
    bgColor[0] = 0.12f; bgColor[1] = 0.12f; bgColor[2] = 0.12f;

    worldCenterX = 0.0; worldCenterY = 0.0; worldCenterZ = 0.0;
    worldRadius = 1.0;
}

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wattributes"
Renderer::~Renderer() {
    m_destroying = true; // suppress signal emissions during teardown
    clearMeshes();
    if (shaderProgram) glDeleteProgram(shaderProgram);
    if (colormapTex) glDeleteTextures(1, &colormapTex);
    gizmo.shutdown();
}

#pragma GCC diagnostic pop

void Renderer::initGLAD() {
    // Harvest the current active OpenGL context created by the Qt Quick Scene Graph thread
    QOpenGLContext* currentContext = QOpenGLContext::currentContext();
    if (!currentContext) {
        qFatal("Fatal: initGLAD called but no active Qt OpenGL context was found on this thread.");
        return;
    }

    // Pass the lambda directly as a function pointer without any reinterpret_cast.
    // The compiler automatically converts a non-capturing lambda into a matching raw function pointer.
    GLADloadproc loader = [](const char* name) -> void* {
        QOpenGLContext* ctx = QOpenGLContext::currentContext();
        return ctx ? reinterpret_cast<void*>(ctx->getProcAddress(name)) : nullptr;
    };

    if (!gladLoadGLLoader(loader)) {
        qFatal("Fatal: GLAD failed to map target core OpenGL function addresses using Qt resolver hook.");
    }

    // ponytail: diagnostic to confirm desktop vs ANGLE/ES context after launch.
    qDebug() << "[GL DIAGNOSTIC] VERSION:" << (const char*)glGetString(GL_VERSION)
             << "| RENDERER:" << (const char*)glGetString(GL_RENDERER)
             << "| GLSL:" << (const char*)glGetString(GL_SHADING_LANGUAGE_VERSION);
}

std::string Renderer::readShaderFile(const std::string& filePath) {
    std::ifstream file(filePath);
    if (!file.is_open()) {
        std::cerr << "Failed to open shader source file: " << filePath << std::endl;
        return "";
    }
    std::stringstream buffer;
    buffer << file.rdbuf();
    return buffer.str();
}

void Renderer::initShaders() {
    // Helper lambda to safely read the shader text straight from the QRC binary resource package
    auto loadEmbeddedShader = [](const QString& rscPath) -> std::string {
        QFile file(rscPath);
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
            qCritical() << "Fatal Error: Required engine shader asset missing at path:" << rscPath;
            return "";
        }
        QTextStream stream(&file);
        return stream.readAll().toStdString();
    };

    // Pull sources via the virtual module path generated by qt_add_qml_module
    std::string vertSrcStr = loadEmbeddedShader(":/RendererQTUI/src/shaders/mesh.vert");
    std::string fragSrcStr = loadEmbeddedShader(":/RendererQTUI/src/shaders/mesh.frag");

    // Defensive crash guard against empty file reads
    if (vertSrcStr.empty() || fragSrcStr.empty()) {
        qFatal("Shader compilation aborted due to unreadable file streams.");
        return;
    }

    const char* vertSrc = vertSrcStr.c_str();
    const char* fragSrc = fragSrcStr.c_str();

    GLuint vert = glCreateShader(GL_VERTEX_SHADER);
    GLuint frag = glCreateShader(GL_FRAGMENT_SHADER);

    if (!compileShader(vert, vertSrc, "VERTEX") || !compileShader(frag, fragSrc, "FRAGMENT")) {
        glDeleteShader(vert);
        glDeleteShader(frag);
        return;
    }

    shaderProgram = glCreateProgram();
    glAttachShader(shaderProgram, vert);
    glAttachShader(shaderProgram, frag);
    glLinkProgram(shaderProgram);

    GLint success;
    glGetProgramiv(shaderProgram, GL_LINK_STATUS, &success);
    if (!success) {
        char log[512];
        glGetProgramInfoLog(shaderProgram, 512, nullptr, log);
        printf("Shader program linking error: %s\n", log);
    }

    glDeleteShader(vert);
    glDeleteShader(frag);

    // Uniform Caching Passes
    // NOTE: Names MUST match the GLSL declarations in src/shaders/mesh.{vert,frag}
    mvpLoc = glGetUniformLocation(shaderProgram, "uMVP");
    modelLoc = glGetUniformLocation(shaderProgram, "uModel");
    viewLoc = glGetUniformLocation(shaderProgram, "uView");
    lightDirLoc = glGetUniformLocation(shaderProgram, "uLightDir");
    viewPosLoc = glGetUniformLocation(shaderProgram, "uViewPos");
    wireframeLoc = glGetUniformLocation(shaderProgram, "uWireframe");
    colorLoc = glGetUniformLocation(shaderProgram, "uMeshColor");
    surfaceColorLoc = glGetUniformLocation(shaderProgram, "uSurfaceColor");

    lightFillLoc = glGetUniformLocation(shaderProgram, "uLightFill");
    lightBack1Loc = glGetUniformLocation(shaderProgram, "uLightBack1");
    lightBack2Loc = glGetUniformLocation(shaderProgram, "uLightBack2");
    lightHeadLoc = glGetUniformLocation(shaderProgram, "uLightHead");

    matAmbientLoc = glGetUniformLocation(shaderProgram, "uMatAmbient");
    matDiffuseLoc = glGetUniformLocation(shaderProgram, "uMatDiffuse");
    matSpecularLoc = glGetUniformLocation(shaderProgram, "uMatSpecular");
    matShininessLoc = glGetUniformLocation(shaderProgram, "uMatShininess");

    keyIntensityLoc = glGetUniformLocation(shaderProgram, "uKeyIntensity");
    fillIntensityLoc = glGetUniformLocation(shaderProgram, "uFillIntensity");
    headIntensityLoc = glGetUniformLocation(shaderProgram, "uHeadIntensity");
    backIntensityLoc = glGetUniformLocation(shaderProgram, "uBackIntensity");

    keyColorLoc = glGetUniformLocation(shaderProgram, "uKeyColor");
    fillColorLoc = glGetUniformLocation(shaderProgram, "uFillColor");
    backColorLoc = glGetUniformLocation(shaderProgram, "uBackColor");
    headColorLoc = glGetUniformLocation(shaderProgram, "uHeadColor");

    sliceHeightXLoc = glGetUniformLocation(shaderProgram, "uSliceHeightX");
    sliceHeightYLoc = glGetUniformLocation(shaderProgram, "uSliceHeightY");
    sliceHeightZLoc = glGetUniformLocation(shaderProgram, "uSliceHeightZ");
    invertXLoc = glGetUniformLocation(shaderProgram, "uInvertX");
    invertYLoc = glGetUniformLocation(shaderProgram, "uInvertY");
    invertZLoc = glGetUniformLocation(shaderProgram, "uInvertZ");
    filterMinLoc = glGetUniformLocation(shaderProgram, "uFilterMin");
    filterMaxLoc = glGetUniformLocation(shaderProgram, "uFilterMax");
    clipEnabledLoc = glGetUniformLocation(shaderProgram, "uClipEnabled");

    scalarMinLoc = glGetUniformLocation(shaderProgram, "uScalarMin");
    scalarMaxLoc = glGetUniformLocation(shaderProgram, "uScalarMax");
    hasScalarsLoc = glGetUniformLocation(shaderProgram, "uHasScalars");
    lutTextureLoc = glGetUniformLocation(shaderProgram, "uColormapLUT");
}

void Renderer::initGizmo() {
    gizmo.init();
}

void Renderer::uploadMesh(const RenderMesh& renderMesh) {
    // WIPE OUT OLD OPENGL HANDLES BEFORE GENERATING NEW ONES
    // Guarded by meshGLMutex so it cannot race with clearMeshes() on the UI thread.
    {
        std::lock_guard<std::mutex> lock(meshGLMutex);
        for (auto& m : meshes) {
            glDeleteVertexArrays(1, &m.vao);
            glDeleteBuffers(1, &m.vbo);
            glDeleteBuffers(1, &m.nbo);
            glDeleteBuffers(1, &m.ebo);
            if (m.sbo) glDeleteBuffers(1, &m.sbo);
        }
        meshes.clear(); // Empty the graphics tracking vector cleanly
    }

    Mesh mesh;
    mesh.indexCount = static_cast<int>(renderMesh.indices.size());

    glGenVertexArrays(1, &mesh.vao);
    glGenBuffers(1, &mesh.vbo);
    glGenBuffers(1, &mesh.nbo);
    glGenBuffers(1, &mesh.ebo);

    glBindVertexArray(mesh.vao);

    glBindBuffer(GL_ARRAY_BUFFER, mesh.vbo);
    glBufferData(GL_ARRAY_BUFFER, renderMesh.vertices.size() * sizeof(float), renderMesh.vertices.data(), GL_STATIC_DRAW);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(0);

    glBindBuffer(GL_ARRAY_BUFFER, mesh.nbo);
    glBufferData(GL_ARRAY_BUFFER, renderMesh.normals.size() * sizeof(float), renderMesh.normals.data(), GL_STATIC_DRAW);
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(1);

    if (!renderMesh.scalars.empty()) {
        glGenBuffers(1, &mesh.sbo);
        glBindBuffer(GL_ARRAY_BUFFER, mesh.sbo);
        glBufferData(GL_ARRAY_BUFFER, renderMesh.scalars.size() * sizeof(float), renderMesh.scalars.data(), GL_STATIC_DRAW);
        glVertexAttribPointer(2, 1, GL_FLOAT, GL_FALSE, sizeof(float), (void*)0);
        glEnableVertexAttribArray(2);
        meshHasScalars = true;
    } else {
        mesh.sbo = 0;
        meshHasScalars = false;
    }

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mesh.ebo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, renderMesh.indices.size() * sizeof(unsigned int), renderMesh.indices.data(), GL_STATIC_DRAW);

    glBindVertexArray(0);
    meshes.push_back(mesh);
}

void Renderer::destroyMesh(Mesh& mesh) {
    glDeleteVertexArrays(1, &mesh.vao);
    glDeleteBuffers(1, &mesh.vbo);
    glDeleteBuffers(1, &mesh.nbo);
    glDeleteBuffers(1, &mesh.ebo);
    if (mesh.sbo) glDeleteBuffers(1, &mesh.sbo);
}

// 1. Rewrite clearMeshes to be strictly for UI/Reset calls (Runs on GUI Thread)
void Renderer::clearMeshes() {
    // Free GPU resources for any uploaded meshes. Guarded by meshGLMutex so it
    // cannot race with uploadMesh() running on the render thread.
    {
        std::lock_guard<std::mutex> lock(meshGLMutex);
        for (auto& m : meshes) {
            destroyMesh(m);
        }
        meshes.clear();
    }
    hasMeshLoaded = false;
    meshHasScalars = false;
    triangleCount = 0;
    pointCount = 0;
    currentMeshName = "";
    if (!m_destroying) emit meshLoadStateChanged();
}

void Renderer::loadMesh(const QString& filePath) {
    if (filePath.isEmpty()) return;

    std::string stdPath = filePath.toStdString();
    if (stdPath.rfind("file:///", 0) == 0) {
        stdPath = stdPath.substr(8);
    } else if (stdPath.rfind("file://", 0) == 0) {
        stdPath = stdPath.substr(7);
    }

    RenderMesh loaded = loadMeshFile(stdPath);
    if (loaded.vertices.empty()) {
        std::cerr << "Engine aborted mapping out invalid/empty file path target: " << stdPath << std::endl;
        return;
    }

    // Thread-safe handoff of the CPU geometry data
    {
        std::lock_guard<std::mutex> lock(meshQueueMutex);
        dynamicMeshQueue = loaded;
    }

    // Cache the source mesh so scalar-field queries (getAvailableScalars,
    // setActiveScalarFieldStd) operate on real data rather than an empty struct.
    cachedMeshSource = loaded;

    // Update dimensions and properties safely on the UI thread
    worldMinX = loaded.bounds.minX; worldMaxX = loaded.bounds.maxX;
    worldMinY = loaded.bounds.minY; worldMaxY = loaded.bounds.maxY;
    worldMinZ = loaded.bounds.minZ; worldMaxZ = loaded.bounds.maxZ;

    worldCenterX = loaded.bounds.centerX;
    worldCenterY = loaded.bounds.centerY;
    worldCenterZ = loaded.bounds.centerZ;
    worldRadius  = loaded.bounds.worldRadius;

    QFileInfo fileInfo(filePath);
    currentMeshName = fileInfo.fileName().toStdString();
    triangleCount = static_cast<int>(loaded.indices.size() / 3);
    pointCount = static_cast<int>(loaded.vertices.size() / 3); // ponytail: vertices are xyz triples

    // UI components read these variables immediately
    hasMeshLoaded = true;

    // NOTE: meshChanged is an atomic flag consumed by the render thread in
    // consumeMeshChanged(); set it so the queued mesh gets uploaded.
    this->meshChanged = true;

    if (!loaded.scalars.empty()) {
        meshHasScalars = true;
        activeScalarName = loaded.scalarName;
        float minVal = loaded.scalars[0];
        float maxVal = loaded.scalars[0];
        for (float val : loaded.scalars) {
            if (val < minVal) minVal = val;
            if (val > maxVal) maxVal = val;
        }
        dataScalarMin = minVal;
        dataScalarMax = maxVal;
        scalarMin = dataScalarMin;
        scalarMax = dataScalarMax;
        // ponytail: default filter spans the whole field so enabling clipping doesn't blank the mesh
        filterMin = dataScalarMin;
        filterMax = dataScalarMax;
    } else {
        meshHasScalars = false;
        dataScalarMin = 0.0f;
        dataScalarMax = 1.0f;
    }

    resetCamera();

    emit meshLoadStateChanged();

    // 2. Alert the CustomViewportItem to trigger a Scene Graph update
    emit meshDataUpdated();
}

void Renderer::resetCamera() {
    // 1. Point the camera's focal target directly at the center of the loaded mesh
    camera.focalPoint = glm::dvec3(worldCenterX, worldCenterY, worldCenterZ);

    // 2. Determine an ideal camera setback distance based on the mesh's bounding radius
    // A standard factor is ~2.5 to 3.0 times the radius to clear the field of view (FOV)
    camera.distance = worldRadius * 2.5;
    if (camera.distance < 1.0) {
        camera.distance = 1.0; // Prevent the camera from nesting inside a flat/empty mesh
    }
    // ponytail: near/far must bracket the real geometry — hardcoding far=100 clipped large meshes into the void
    nearPlane = std::max(0.01, worldRadius * 0.001);
    farPlane  = std::max(100.0, worldRadius * 10.0);

    // 3. Reset the position vector relative to the focal point along the Z axis
    camera.position = camera.focalPoint + glm::dvec3(0.0, 0.0, camera.distance);

    // 4. Force a clean baseline view orientation (Up vector along +Y axis)
    camera.viewUp = glm::dvec3(0.0, 1.0, 0.0);
    camera.orthogonalizeViewUp();

    // 5. Trigger a viewport update if a window context is currently active
    // (If your header declares resetCamera as a slot, you can also emit cameraChanged() here)
}

void Renderer::resizeViewport(int w, int h) {
    width = w;
    height = h;
}

void Renderer::computeLightDirections(glm::vec3& key, glm::vec3& fill, glm::vec3& back1, glm::vec3& back2, glm::vec3& head) {
    auto toRad = [](float deg) { return deg * 3.14159265f / 180.0f; };
    auto calcDir = [&](float az, float el) {
        float a = toRad(az);
        float e = toRad(el);
        return glm::normalize(glm::vec3(std::sin(a) * std::cos(e), std::sin(e), std::cos(a) * std::cos(e)));
    };
    key = calcDir(lightKeyAzimuth, lightKeyElevation);
    fill = calcDir(lightFillAzimuth, lightFillElevation);
    back1 = calcDir(lightBackAzimuth, lightBackElevation);
    back2 = calcDir(lightBackAzimuth + 180.0f, -lightBackElevation);
    head = calcDir(lightHeadAzimuth, lightHeadElevation);
}

void Renderer::updateColormapTexture() {
    if (colormapChoice == lastUploadedChoice && colormapTex != 0) return;

    // Dynamically sample 256 structural elements across procedural math maps
    std::vector<unsigned char> paletteData;
    paletteData.reserve(256 * 3);

    for (int i = 0; i < 256; ++i) {
        float t = static_cast<float>(i) / 255.0f;
        glm::vec3 rgb = Colormaps::evaluate(t, static_cast<ColormapType>(colormapChoice));
        paletteData.push_back(static_cast<unsigned char>(rgb.r * 255.0f));
        paletteData.push_back(static_cast<unsigned char>(rgb.g * 255.0f));
        paletteData.push_back(static_cast<unsigned char>(rgb.b * 255.0f));
    }

    if (colormapTex == 0) {
        glGenTextures(1, &colormapTex);
    }
    glBindTexture(GL_TEXTURE_1D, colormapTex);
    glTexImage1D(GL_TEXTURE_1D, 0, GL_RGB, 256, 0, GL_RGB, GL_UNSIGNED_BYTE, paletteData.data());
    glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_1D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glBindTexture(GL_TEXTURE_1D, 0);

    lastUploadedChoice = colormapChoice;
}

void Renderer::renderFrame() {
    // Standard buffer setups
    glEnable(GL_DEPTH_TEST);
    glDepthFunc(GL_LESS);
    // ponytail: no face culling — meshes (hexes/structured grids) show inverted/inside faces
    glDisable(GL_CULL_FACE);

    glClearColor(bgColor[0], bgColor[1], bgColor[2], 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    // Establish the full-window viewport for the scene (grid + mesh). The scene
    // draws full-window; set the GL viewport here in device pixels so it matches
    // the real framebuffer on HiDPI displays (width/height are logical).
    int deviceW = static_cast<int>(width * devicePixelRatio);
    int deviceH = static_cast<int>(height * devicePixelRatio);
    glViewport(0, 0, deviceW, deviceH);

    glm::mat4 view = camera.getViewMatrix();
    glm::mat4 proj = glm::perspective(
        glm::radians(45.0f),
        static_cast<float>(deviceW) / static_cast<float>(deviceH),
        static_cast<float>(nearPlane),
        static_cast<float>(farPlane)
        );
    glm::mat4 model = glm::mat4(1.0f);
    glm::mat4 mvp = proj * view * model;

    // Main Mesh Rendering Operations
    if ((showSurface || showWireframe) && !meshes.empty() && shaderProgram != 0) {
        glUseProgram(shaderProgram);
        updateColormapTexture();

        // Pass Matrix Transforms
        glUniformMatrix4fv(mvpLoc, 1, GL_FALSE, glm::value_ptr(mvp));
        glUniformMatrix4fv(modelLoc, 1, GL_FALSE, glm::value_ptr(model));
        glUniformMatrix4fv(viewLoc, 1, GL_FALSE, glm::value_ptr(view));

        // Setup Light Parameters
        // computeLightDirections() returns WORLD-space directions. The shader
        // works in VIEW space (vNormal and viewDir are view-space), so transform
        // the lights through the view rotation. The dot product is then
        // rotation-invariant => world-fixed lighting that does not track the camera.
        glm::mat3 viewRot = glm::mat3(view);
        glm::vec3 kDir, fDir, b1Dir, b2Dir, hDir;
        computeLightDirections(kDir, fDir, b1Dir, b2Dir, hDir);
        kDir  = glm::normalize(viewRot * kDir);
        fDir  = glm::normalize(viewRot * fDir);
        b1Dir = glm::normalize(viewRot * b1Dir);
        b2Dir = glm::normalize(viewRot * b2Dir);
        hDir  = glm::normalize(viewRot * hDir);
        glUniform3fv(lightDirLoc, 1, glm::value_ptr(kDir));
        glUniform3fv(lightFillLoc, 1, glm::value_ptr(fDir));
        glUniform3fv(lightBack1Loc, 1, glm::value_ptr(b1Dir));
        glUniform3fv(lightBack2Loc, 1, glm::value_ptr(b2Dir));
        glUniform3fv(lightHeadLoc, 1, glm::value_ptr(hDir));

        glm::vec3 camPos = glm::vec3(camera.position);
        glUniform3fv(viewPosLoc, 1, glm::value_ptr(camPos));

        // Assign Shading Registers
        glUniform3fv(colorLoc, 1, meshColor);
        glUniform3fv(surfaceColorLoc, 1, surfaceColor);
        glUniform1f(matAmbientLoc, matAmbient);
        glUniform1f(matDiffuseLoc, matDiffuse);
        glUniform1f(matSpecularLoc, matSpecular);
        // matShininess is a 0..1 "shininess" factor; the shader converts it to an
        // exponent via pow(2.0, uMatShininess * 10.0). Pass the raw factor so the
        // two sides agree on the convention.
        glUniform1f(matShininessLoc, matShininess);

        glUniform1f(keyIntensityLoc, lightInt * lightKF);
        glUniform1f(fillIntensityLoc, lightInt * lightKB);
        glUniform1f(headIntensityLoc, lightInt * lightKH);
        glUniform1f(backIntensityLoc, lightInt * lightKB);

        // Light kit colors (warm-white key/fill/head, neutral back) so the
        // diffuse/specular terms are non-zero and the mesh is actually lit.
        const float keyCol[3] = { 1.0f, 0.96f, 0.88f };
        const float fillCol[3] = { 0.85f, 0.9f, 1.0f };
        const float backCol[3] = { 0.9f, 0.9f, 0.95f };
        const float headCol[3] = { 1.0f, 1.0f, 1.0f };
        glUniform3fv(keyColorLoc, 1, keyCol);
        glUniform3fv(fillColorLoc, 1, fillCol);
        glUniform3fv(backColorLoc, 1, backCol);
        glUniform3fv(headColorLoc, 1, headCol);

        // Assign Dynamic Clip Slices Filters
        glUniform1f(sliceHeightXLoc, sliceHeightX);
        glUniform1f(sliceHeightYLoc, sliceHeightY);
        glUniform1f(sliceHeightZLoc, sliceHeightZ);
        glUniform1i(invertXLoc, invertX ? 1 : 0);
        glUniform1i(invertYLoc, invertY ? 1 : 0);
        glUniform1i(invertZLoc, invertZ ? 1 : 0);
        glUniform1f(filterMinLoc, filterMin);
        glUniform1f(filterMaxLoc, filterMax);
        glUniform1i(clipEnabledLoc, clipEnabled ? 1 : 0);

        glUniform1f(scalarMinLoc, scalarMin);
        glUniform1f(scalarMaxLoc, scalarMax);
        glUniform1i(hasScalarsLoc, meshHasScalars ? 1 : 0);

        if (meshHasScalars && colormapTex != 0) {
            glActiveTexture(GL_TEXTURE0);
            glBindTexture(GL_TEXTURE_1D, colormapTex);
            glUniform1i(lutTextureLoc, 0);
        }

        for (const auto& m : meshes) {
            glBindVertexArray(m.vao);

            // Phase 1: Solid Base Pass (only when surface shown)
            if (showSurface) {
                glUniform1i(wireframeLoc, 0);
                glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                glDrawElements(GL_TRIANGLES, m.indexCount, GL_UNSIGNED_INT, 0);
            }

            // Phase 2: Structural Wireframe Layer Overlay
            if (showWireframe) {
                glUniform1i(wireframeLoc, 1);
                glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                glEnable(GL_POLYGON_OFFSET_LINE);
                glPolygonOffset(-1.0f, -1.0f);
                glDrawElements(GL_TRIANGLES, m.indexCount, GL_UNSIGNED_INT, 0);
                glDisable(GL_POLYGON_OFFSET_LINE);
            }
        }
        glBindVertexArray(0);
        glUseProgram(0);
    }

    drawGizmo();

    // CRITICAL CORE SYNC FIX: Restore standard Qt Quick scene graph drawing states
    QQuickOpenGLUtils::resetOpenGLState();
}

void Renderer::drawGizmo() {
    // Pure low-level overlay: isolated corner viewport, rotation-only view, raw GL.
    glDisable(GL_DEPTH_TEST);
    gizmo.draw(camera.getViewMatrix(), static_cast<float>(devicePixelRatio),
               static_cast<int>(height * devicePixelRatio));
    glEnable(GL_DEPTH_TEST);
}

void Renderer::snapToOrthoView(int axis) {
    // Delegate to the Camera implementation so both stay in sync (6-axis support).
    camera.snapToOrthoView(axis);
    emit viewChanged(); // ponytail: ortho snap must repaint; snapToAxisView already does this
}

void Renderer::snapToAxisView(int axis, bool flip) {
    int preset = flip ? (axis * 2 + 1) : (axis * 2);
    camera.snapToOrthoView(preset);
    emit viewChanged();
}

void Renderer::requestScreenshot(const QString& path) {
    if (path.isEmpty()) {
        return;
    }
    // ponytail: the actual GL pixel read + save is unsafe here (GUI thread, no GL
    // context). Forward to the render thread (CustomViewportItem connects
    // screenshotRequested -> render() where the context is current).
    emit screenshotRequested(path);
}

bool Renderer::captureScreenshotToFile(const QString& path) {
    if (path.isEmpty()) return false;

    ExportConfig config;
    config.transparentBackground = false;
    config.quality = 95;
    config.format = ExportFormat::PNG;

    QString targetPath = path;
    if (targetPath.endsWith(".jpg", Qt::CaseInsensitive) || targetPath.endsWith(".jpeg", Qt::CaseInsensitive)) {
        config.format = ExportFormat::JPEG;
    } else if (targetPath.endsWith(".bmp", Qt::CaseInsensitive)) {
        config.format = ExportFormat::BMP;
    } else {
        config.format = ExportFormat::PNG;
        if (!targetPath.endsWith(".png", Qt::CaseInsensitive)) {
            targetPath += ".png";
        }
    }
    config.filePath = targetPath;

    // Called on the render thread with the GL context current. Use device-pixel
    // dimensions so the captured image matches the real framebuffer.
    // When rendered via QQuickFramebufferObject, the scene graph has its own FBO
    // bound (not the default 0), so read from whatever is currently bound.
    GLint boundFbo = 0;
    glGetIntegerv(GL_FRAMEBUFFER_BINDING, &boundFbo);
    int deviceW = static_cast<int>(width * devicePixelRatio);
    int deviceH = static_cast<int>(height * devicePixelRatio);
    std::vector<unsigned char> pixels = ScreenshotExporter::captureFBO(boundFbo, deviceW, deviceH, config.transparentBackground);

    bool success = ScreenshotExporter::saveToFile(config.filePath, pixels, deviceW, deviceH, config);
    if (success) {
        emit screenshotCaptured(targetPath);
    }
    return success;
}

QStringList Renderer::getAvailableScalars() const {
    QStringList list;
    for (const auto& name : cachedMeshSource.availableScalarNames) {
        list.append(QString::fromStdString(name));
    }
    return list;
}

QStringList Renderer::getColormapNames() const {
    QStringList list;
    for (int i = 0; i < static_cast<int>(ColormapType::Count); ++i) {
        list.append(QString::fromUtf8(Colormaps::getName(static_cast<ColormapType>(i))));
    }
    return list;
}

QVariantList Renderer::getColormapStops() const {
    QVariantList out;
    const int steps = 16;
    for (int i = 0; i <= steps; ++i) {
        float t = static_cast<float>(i) / static_cast<float>(steps);
        glm::vec3 c = Colormaps::evaluate(t, static_cast<ColormapType>(colormapChoice));
        QVariantList stop;
        stop << t << c.r << c.g << c.b;
        out.append(QVariant(stop));
    }
    return out;
}

std::vector<std::string> Renderer::getAvailableScalarNames() const {
    std::vector<std::string> list;
    if (!cachedMeshSource.scalarName.empty()) {
        list.push_back(cachedMeshSource.scalarName);
    }
    return list;
}

void Renderer::setActiveScalarField(const QString& fieldName) {
    setActiveScalarFieldStd(fieldName.toStdString());
}

void Renderer::setActiveScalarFieldStd(const std::string& fieldName) {
    if (fieldName == activeScalarName) return;
    // ponytail: fields live in pointScalars; swap the active vector and let the
    // existing render-thread upload path (meshChanged) push the new sbo.
    auto it = cachedMeshSource.attributes->pointScalars.find(fieldName);
    if (it == cachedMeshSource.attributes->pointScalars.end()) return;

    activeScalarName = fieldName;
    cachedMeshSource.scalarName = fieldName;
    cachedMeshSource.scalars = it->second;
    dynamicMeshQueue.scalarName = fieldName;
    dynamicMeshQueue.scalars = it->second;

    if (!cachedMeshSource.scalars.empty()) {
        float mn = cachedMeshSource.scalars[0], mx = cachedMeshSource.scalars[0];
        for (float v : cachedMeshSource.scalars) { if (v < mn) mn = v; if (v > mx) mx = v; }
        dataScalarMin = mn; dataScalarMax = mx;
        scalarMin = mn; scalarMax = mx;
        filterMin = mn; filterMax = mx;
    }
    meshChanged = true; // ponytail: trigger GPU re-upload of the scalar buffer
    emit meshDataUpdated();
}

void Renderer::setWireframe(bool enabled) {
    if (showWireframe == enabled) return;
    showWireframe = enabled;
    emit wireframeChanged();
}

void Renderer::toggleSurface(bool visible) {
    if (showSurface == visible) return;
    showSurface = visible;
    emit surfaceVisibilityChanged();
}

void Renderer::setColormapChoice(int choice) {
    if (colormapChoice == choice) return;
    colormapChoice = choice;
    emit colormapChanged();
}
